# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cauchyP <- function(P) {
    .Call('_lit_cauchyP', PACKAGE = 'lit', P)
}

.pairwise_prod <- function(x) {
    .Call('_lit_pairwise_prod', PACKAGE = 'lit', x)
}

.quick_lm_cpp <- function(Xs, Ys) {
    .Call('_lit_quick_lm_cpp', PACKAGE = 'lit', Xs, Ys)
}

.lit_cpp <- function(Xs, Ys, Hs) {
    .Call('_lit_lit_cpp', PACKAGE = 'lit', Xs, Ys, Hs)
}

.marginal_internal <- function(Xs, Ys, Hs) {
    .Call('_lit_marginal_internal', PACKAGE = 'lit', Xs, Ys, Hs)
}

.lit_bed_cpp <- function(file, m_loci, n_ind, sY, sH, verbose) {
    .Call('_lit_lit_bed_cpp', PACKAGE = 'lit', file, m_loci, n_ind, sY, sH, verbose)
}

.gamut_bed_cpp <- function(file, m_loci, n_ind, sY, sH, verbose) {
    .Call('_lit_gamut_bed_cpp', PACKAGE = 'lit', file, m_loci, n_ind, sY, sH, verbose)
}

.marginal_bed_cpp <- function(file, m_loci, n_ind, sY, sH, tot, verbose) {
    .Call('_lit_marginal_bed_cpp', PACKAGE = 'lit', file, m_loci, n_ind, sY, sH, tot, verbose)
}

